version: "3"

services:
  weather-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - RATE_LIMIT_CALL=60
      - RATE_LIMIT_PERIOD=60
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always